version: "3.9"

services:

  api-02-calculo-juros:
    image: marciomm/softplayer-api-02-calculo-juros
    container_name: api-02-calculo-juros
    build:
      context: ../src
      dockerfile: ./Services/CalculoJuros/MMM.Teste.CalculoJuros.Api/Dockerfile
    restart: always 
    ports:
      - "5101:5101"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5101
      
  api-01-taxa-juros:
    image: marciomm/softplayer-api-01-taxa-juros
    container_name: api-01-taxa-juros
    build:
      context: ../src
      dockerfile: ./Services/TaxaJuros/MMM.Test.TaxaJuros/Dockerfile
    restart: always 
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001


